# 应用服务 WEB 访问端口
server:
  port: 8123
  servlet:
    context-path: /api
wuapi:
  client:
    access-key: wuyan
    secret-key: abcdefgh
logging:
    level:
      org.springframework:
        boot:
          autoconfigure:
            logging: info