server:
  port: 8090


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
      default-filters:
        - AddResponseHeader=source,wuyan


# 以下配置指定了应用的名称、使用的协议（Dubbo）、随机端口、注册中心的类型（Nacos）和地址
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 23457
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
  consumer:
    timeout:
      3000